// Frontend/vue/src/ui/Button.vue
<template>
  <md-button
    class="md-raised"
    v-if="condition(uiElement)"
    v-bind:class="uiElement.class"
    v-bind:style="uiElement.style"
    @click="click($event)"
  >{{uiElement.label}}</md-button>
</template>

<script>
const obj = require('object-path');
export default {
  props: ["uiElement", "data"],
  inject: ["config", "event"],
  methods: {
    condition: function(uiElement) {
      let passed = true;
      if (uiElement.condition) {
        passed = eval(uiElement.condition);
      }
      return passed;
    },
    click: async function(event, item, script) {
      let clickScript = script ? script : this.uiElement.click;
      if (clickScript) {
        try {
          await eval(clickScript);
        } catch (e) {
          console.error(e);
        }
      }
    }
  },
  computed: {
    event: function(sender) {
      return {
        send: function(e) {
          _event.send(e.name, e);
        }
      };
    }
  }
};
</script>

// Frontend/angular14/src/app/ui/button/button.component.ts
// @ts-nocheck
import { Component } from "@angular/core";
import { BaseComponent } from "../base.component";

@Component({
  selector: "button-component",
  templateUrl: "./button.component.html",
})
export class ButtonComponent extends BaseComponent {
  async click(event, item?, script?) {
    let clickScript = script ? script : this.uiElement.click;
    if (clickScript) {
      try {
        eval(clickScript);
      } catch (e) {
        this.event.send({ name: "error", error: `${e} ${e.stack}` });
        console.log(e);
      }
    }
  }
}

<button *ngIf="
    (!uiElement.buttonType || uiElement.buttonType == 'mat-raised-button') &&
    condition(uiElement)
  " mat-raised-button [disabled]="uiElement.disabled == true" [matTooltip]="uiElement.tooltip"
  (click)="click.call(this, $event)" [color]="uiElement.color" [ngStyle]="uiElement.style"
  [tabIndex]="uiElement.tabIndex ? uiElement.tabIndex : -1">
  <mat-icon *ngIf="uiElement.icon" [ngStyle]="uiElement.iconStyle" [inline]="true">{{
    uiElement.icon
    }}</mat-icon>
  {{ uiElement.label }}
</button>

<button *ngIf="uiElement.buttonType == 'mat-button' && condition(uiElement)" mat-button
  [disabled]="uiElement.disabled == true" [matTooltip]="uiElement.tooltip" (click)="click($event)"
  [color]="uiElement.color" [ngStyle]="uiElement.style" [tabIndex]="uiElement.tabIndex ? uiElement.tabIndex : -1">
  <mat-icon *ngIf="uiElement.icon" [ngStyle]="uiElement.iconStyle" [inline]="true">{{
    uiElement.icon
    }}</mat-icon>
  {{ uiElement.label }}
</button>

<button *ngIf="uiElement.buttonType == 'mat-icon-button' && condition(uiElement)" mat-icon-button
  [disabled]="uiElement.disabled == true" [matTooltip]="uiElement.tooltip" (click)="click($event)"
  [color]="uiElement.color" [ngStyle]="uiElement.style" [tabIndex]="uiElement.tabIndex ? uiElement.tabIndex : -1">
  <mat-icon *ngIf="uiElement.icon" [ngStyle]="uiElement.iconStyle" [matBadge]="safeGet(uiElement, 'matBadge', '')"
    [matBadgePosition]="safeGet(uiElement, 'matBadgePosition', '')"
    [matBadgeColor]="safeGet(uiElement, 'matBadgeColor', '')" [inline]="true">{{ eval(uiElement.icon) }}</mat-icon>
</button>

<button *ngIf="uiElement.buttonType == 'mat-fab' && condition(uiElement)" mat-fab
  [disabled]="uiElement.disabled == true" [matTooltip]="uiElement.tooltip" (click)="click($event)"
  [color]="uiElement.color" [ngStyle]="uiElement.style" [tabIndex]="uiElement.tabIndex ? uiElement.tabIndex : -1">
  <mat-icon *ngIf="uiElement.icon" [ngStyle]="uiElement.iconStyle" [inline]="true">{{
    eval(uiElement.icon)
    }}</mat-icon>
  {{ uiElement.label }}
</button>

<button *ngIf="uiElement.buttonType == 'mat-mini-fab' && condition(uiElement)" mat-mini-fab
  [disabled]="uiElement.disabled == true" [matTooltip]="uiElement.tooltip" (click)="click($event)"
  [color]="uiElement.color" [ngStyle]="uiElement.style" [tabIndex]="uiElement.tabIndex ? uiElement.tabIndex : -1">
  <mat-icon *ngIf="uiElement.icon" [ngStyle]="uiElement.iconStyle" [inline]="true">{{
    eval(uiElement.icon)
    }}</mat-icon>
  {{ uiElement.label }}
</button>

<button *ngIf="uiElement.buttonType == 'mat-menu-item' && condition(uiElement)" mat-menu-item
  [disabled]="uiElement.disabled == true" [matTooltip]="uiElement.tooltip" (click)="click($event)"
  [ngStyle]="uiElement.style" [tabIndex]="uiElement.tabIndex ? uiElement.tabIndex : -1">
  {{ uiElement.label }}
</button>
