// Frontend/vue/src/ui/Base.vue
<template>
  <div></div>
</template>

<script>
//
const obj = require("object-path");
const moment = require("moment");

export default {
  props: ["uiElement", "data"],
  inject: ["config", "event", "rest", "ui"],
  mounted: function() {
    if (
      this.uiElement &&
      this.uiElement.init
    ) {
      try {
        eval(this.uiElement.init);
      } catch (ex) {
        console.error(ex);
      }
    }
  },
  methods: {
    condition: function(uiElement) {
      let passed = true;
      if (uiElement.condition) {
        passed = eval(uiElement.condition);
      }
      return passed;
    },
    click: function($event, uiElement, item) {
      if (this.uiElement.click) {
        try {
          eval(this.uiElement.click);
        } catch (ex) {
          console.error(ex);
        }
      }
    },
    safeEval(script) {
      try {
        return eval(script);
      } catch (ex) {
        console.error(script, ex);
      }
    }
  }
};
</script>

// Frontend/react/src/ui/Base.js
import React from "react";
import safeEval from "safe-eval";

class Base extends React.Component {
  condition = () => {
    let result = true;
    if (this.uiElement.condition) {
      try {
        result = safeEval(this.uiElement.condition, { ...this });
      } catch (e) {
        result = false;
      }
    }
    return result;
  };

  // format to date on the column
  format(v, transform, row) {
    // transform
    if (transform) {
      try {
        v = safeEval(transform, { ...this });
      } catch (e) {
        console.error(e);
      }
    }
    return v;
  }
}

export default Base;
