// Frontend/vue/src/ui/Typography.vue
<template>
  <div
    v-html="value()"
    @click="click($event)"
    :class="uiElement.class"
    :style="uiElement.style"
  ></div>
</template>

<script>
import Vue from "vue";
import Base from "./Base";
const obj = require("object-path");
const moment = require("moment");

export default Vue.component('typography', {
  extends: Base,
  methods: {
    value: function() {
      let text = null;

      // fixed text
      if (this.uiElement.text) {
        // set value
        text = this.uiElement.text;
      }

      // key exists
      else if (this.data && this.uiElement.key) {
        // set value
        text = obj.get(this.data, this.uiElement.key);
      }

      // if null then assign default
      if (
        (typeof this._value == "undefined" || this._value == null) &&
        this.uiElement.default
      ) {
        text = this.uiElement.default;
        try {
          text = eval(this.uiElement.default);
        } catch {
          //
        }
      }

      // if format is specified
      if (this.uiElement.format) {
        try {
          text = eval(this.uiElement.format);
        } catch (e) {
          console.error(this.uiElement.format, e);
        }
      }

      return text;
    }
  }
});
</script>

// Frontend/angular14/src/app/ui/typography/typography.component.ts
// @ts-nocheck
import { Component, HostListener } from "@angular/core";
import obj from "object-path";

// user Imports
import { BaseComponent } from "../base.component";

@Component({
  selector: "typography",
  template: `
    <div
      *ngIf="value"
      [ngStyle]="uiElement.style"
      [ngClass]="uiElement.class"
      [innerHtml]="value | safe: 'html'"
    ></div>
  `,
})
export class TypographyComponent extends BaseComponent {
  @HostListener("click", [`$event`]) onClick(event) {
    if (obj.has(this.uiElement, "click")) {
      this.click(event, this.data, this.uiElement.click);
    }
  }

  _value;
  get value() {
    // fixed text
    if (this.uiElement.text) {
      // set value
      this._value = this.uiElement.text;
    }

    // key exists
    else if (this.data && this.uiElement.key) {
      // set value
      this._value = obj.get(this.data, this.uiElement.key);
    }

    // if null then assign default
    if (
      (typeof this._value == "undefined" || this._value == null) &&
      this.uiElement.default
    ) {
      this._value = this.uiElement.default;
      try {
        this._value = eval(this.uiElement.default);
      } catch (e) {}
    }

    // read returns local variable because of the format that can change its own value
    // and next time it will try to format the already formatted text <- which is to be prevented
    let v = this._value;

    // if format is specified
    if (this.uiElement.format) {
      try {
        v = eval(this.uiElement.format);
      } catch (e) {
        console.error(this.uiElement.format, e);
      }
    }

    return v;
  }
}
