// Frontend/vue/src/ui/Layout.vue
<template>
  <div
    v-if="condition(uiElement)"
    :class="uiElement.layoutClass"
    :style="uiElement.layoutStyle"
    :id="uiElement.id"
  >
    <UiElement
      v-for="(ui, index) in uiElement.screens"
      :key="index"
      :uiElement="ui"
      :data="data"
    />
  </div>
</template>

<script>
import Vue from "vue";
import Base from "./Base";
const obj = require("object-path");
const moment = require("moment");

export default Vue.component("layout", {
  extends: Base,
});
</script>

// Frontend/angular14/src/app/ui/layout/layout.component.ts
// @ts-nocheck
import { Component, HostListener } from "@angular/core";
import { BaseComponent } from "../base.component";

@Component({
  selector: "layout",
  template: `
    <ng-container *ngFor="let ui of uiElement.screens">
      <ng-container
        ui-element
        *ngIf="condition(ui)"
        [uiElement]="ui"
        [data]="data"
        [style]="uiElement.layoutStyle"
        [class]="uiElement.layoutClass"
      >
      </ng-container>
    </ng-container>
  `,
})
export class LayoutComponent extends BaseComponent {
  @HostListener("click", [`$event`]) onClick(event) {
    if (obj.has(this.uiElement, "click")) {
      this.click(event, this.data, this.uiElement.click);
    }
  }
}
