// Frontend/angular/src/app/layout/login/login.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import * as obj from 'object-path'

// user imports
import { ConfigService } from '../../services/config.service';
import { AuthService } from '../../services/auth.service';
import { EventService } from '../../services/event.service';
import { Subscription } from 'rxjs';

@Component({
  selector: 'login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit, OnDestroy {
  constructor(
    public config: ConfigService
    , private auth: AuthService
    , private event: EventService
  ) {
  }

  // login screen
  screen: any

  // data
  data: any = {}

  onEvent: Subscription
  ngOnInit() {
    // load default login screen
    this.screen = this.config.configuration.login.screen

    // handle events
    this.onEvent = this.event.onEvent.subscribe(
      event => {
        if (event.name == 'login') {
          this.login()
        }
      }
    )
  }

  ngOnDestroy() {
    this.onEvent.unsubscribe()
  }

  // login
  login() {
    // validate input
    this.data.error = '';
    for (let ui of this.screen) {
      let value = this.data[ui.key] // used by the evaluation script
      let error = eval(ui.errorCondition)
      if (error) {
        this.data.error += `${ui.errorMessage}\n`
      }
    }

    // if there are error don't continue
    if (this.data.error) return

    // try login
    this.event.send("splash-show") // show splash
    this.auth.authenticate(this.data).subscribe(
      result => {
        this.event.send("splash-hide") // hide splash
        // evaluate the result
        if (result != true) {
          // login error
          this.data.error = result
        }
        else {
          // login success
          this.event.send('authenticated')
        }
      }
    )
  }

}

<splash></splash>

<div id="login" fxLayout="column">
  <div id="login-form-wrapper" fxLayout="column" fxLayoutAlign="center center">
    <div id="login-form" class="mat-elevation-z16">
      <ng-container *ngFor="let ui of screen">
        <ui-layout-wrapper [uiElement]="ui" [data]="data"></ui-layout-wrapper>
      </ng-container>
    </div>
  </div>
</div>

// Frontend/react/src/layout/Login.js
import React from "react";

// interface
import UILayoutWrapper from "../ui/UILayoutWrapper";

// user imports
import EventService from "../services/event.service";
import ConfigService from "../services/config.service";

export default class Login extends React.Component {
  constructor() {
    super();

    // state
    this.state = {};

    // save as services
    this.event = EventService;
    this.config = ConfigService;
  }

  componentDidMount() {
    // event handler
    this.onEvent = this.event.onEvent.subscribe(event =>
      this.eventHandler(event)
    );
  }

  componentWillUnmount() {
    this.onEvent.unsubscribe();
  }

  eventHandler = async event => {
    if (event.name == "login") {
      if (event.data) this.data = Object.assign(this.data, event.data);
      await this.authenticate();
    }
  };

  // login
  async authenticate() {
    // extract from props
    const { uiElement } = this.props;
    this.uiElement = uiElement;
    this.data = this.state;

    // validate input
    this.data.error = "";
    for (let ui of this.login.screen) {
      let value = this.data[ui.key]; // used by the evaluation script
      if (ui.errorCondition) {
        let error = eval(ui.errorCondition);
        if (error) this.data.error += `${ui.errorMessage}\n`;
      }
    }

    // if there are error don't continue
    if (this.data.error) {
      this.setState(this.data)
      return;
    }

    // try login
    this.event.send("splash-show"); // show splash
    try {
      await this.auth.login(this.data);
      console.log(this.data)
      // login success
      this.event.send("authenticated");
    } catch (e) {
      // login error
      this.data.error = e;
    }
    this.event.send("splash-hide"); // hide splash
  }

  handleMenuClick = () => {
    this.event.send({ name: "drawer-toggle" });
  };

  render() {
    this.login = this.config.get("login");
    let screen;
    if (this.login && this.login.screen) {
      screen = this.login.screen.map((x, i) => {
        return <UILayoutWrapper key={i} uiElement={x} data={this.data} />;
      });
    }

    return (
      <div style={this.login.layoutStyle}>
        <div style={this.login.style} className={this.login.class}>
          {screen}
        </div>
      </div>
    );
  }
}
