// Frontend/vue/src/ui/DataTable.vue
<template>
  <!-- Simple List -->
  <div
    v-if="uiElement.tableType == 'list'"
    :style="uiElement.contentLayoutStyle"
    :class="uiElement.contentLayoutStyle"
  >
    <DynamicScroller
      v-if="uiElement.virtualScroll"
      :items="rows ? rows : []"
      :min-item-size="uiElement.minItemSize?uiElement.minItemSize: 150"
      :key-field="uiElement.keyField?uiElement.keyField:'_id'"
      v-slot="{item}"
    >
      <div
        :style="uiElement.itemBoxStyle"
        :class="uiElement.itemBoxClass"
        @click="click($event, uiElement, item)"
      >
        <UiElement
          v-for="(column, index) in uiElement.columns"
          v-bind:key="index"
          v-bind:uiElement="filterUiElement(column, item)"
          v-bind:data="filterData(column, item)"
        />
      </div>
    </DynamicScroller>

    <div
      v-if="!uiElement.virtualScroll"
      :style="uiElement.contentLayoutStyle"
      :class="uiElement.contentLayoutStyle"
    >
      <div
        v-for="(row, index) of rows"
        v-bind:key="index"
        v-bind:style="uiElement.itemBoxStyle"
        v-bind:class="uiElement.itemBoxClass"
        @click="click($event, uiElement, row)"
      >
        <UiElement
          v-for="(column, index) in uiElement.columns"
          v-bind:key="index"
          v-bind:uiElement="filterUiElement(column, row)"
          v-bind:data="filterData(column, row)"
        />
      </div>
    </div>

    <paginate
      v-if="pageCount > 1"
      :page-count="pageCount"
      :click-handler="changePage"
      :prev-text="'<<'"
      :next-text="'>>'"
      :container-class="'pagination'"
      :page-class="'page-item'"
      :page-link-class="'page-link-item'"
      :prev-class="'prev-item'"
      :prev-link-class="'prev-link-item'"
      :next-class="'next-item'"
      :next-link-class="'next-link-item'"
      :break-view-class="'break-view'"
      :break-view-link-class="'break-view-link'"
    ></paginate>
  </div>
</template>

<script>
import Vue from "vue";
import Base from "./Base";
import Paginate from "vuejs-paginate";
Vue.component("paginate", Paginate);

//
const obj = require("object-path");
const moment = require("moment");

export default {
  extends: Base,
  props: ["uiElement", "data"],
  data: function () {
    return {
      size: 0,
      page: 0,
      total: 0,
    };
  },
  mounted: function () {
    // subscribe to refresh
    if (this.uiElement.key) {
      this.event.subscribe(this.uiElement.key, "refresh", () => {
        this.requestDownload();
      });
    }

    // download request
    this.requestDownload();
  },
  destroyed: function () {
    if (this.uiElement.key) {
      this.event.unsubscribe_all(this.uiElement.key);
    }
  },
  methods: {
    async requestDownload() {
      // load initial configuration
      if (this.uiElement.src) {
        let src = this.uiElement.src;
        try {
          src = eval(src);
        } catch (ex) {
          //
          console.error(ex);
        }

        let method = obj.get(this.uiElement, "method", "get");

        // pagination
        this.size = obj.get(this.uiElement, "size", 10);
        if (!this.page) {
          this.page = obj.get(this.uiElement, "page", 1);
        }
        let data = {
          size: this.size,
          page: this.page,
        };

        //
        this.event.send({ name: "splash-show" });
        let response = await this.rest.request(src, data, method);
        response = response.data;
        if (this.uiElement.transform) {
          try {
            this.rows = eval(this.uiElement.transform);
          } catch (ex) {
            console.error(ex);
          }
        } else {
          this.rows = response;
        }

        // get total records
        let transformTotal = this.uiElement.transformTotal || "response.total";
        try {
          this.total = parseInt(eval(transformTotal));
        } catch (e) {}
        if (this.total != 0 && !this.total)
          this.total = obj.get(this, "rows", []).length;

        this.event.send({ name: "splash-hide" });
        this.event.send({ name: "data", data: this.data });
      }
    },
    async changePage(pageNum) {
      this.page = pageNum;
      await this.requestDownload();
    },
    filterUiElement(uiElement, data) {
      if (uiElement.filterUiElement) {
        try {
          eval(uiElement.filterUiElement);
        } catch (ex) {
          console.error(ex);
        }
      }
      return uiElement;
    },
    filterData(uiElement, data) {
      if (uiElement.filterData) {
        try {
          eval(uiElement.filterData);
        } catch (ex) {
          console.error(ex);
        }
      }
      return data;
    },
  },
  computed: {
    rows: {
      get: function () {
        let rows = [];
        if (this.data && this.uiElement.key) {
          rows = obj.get(this.data, this.uiElement.key);
        }

        if (typeof this._rows != "undefined" && !Array.isArray(this._rows))
          rows = [rows];

        return rows;
      },
      set: function (v) {
        if (this.data && this.uiElement.key) {
          obj.set(this.data, this.uiElement.key, v);
        }
      },
    },
    pageCount: {
      get: function () {
        return (
          (this.total == 0 ? 1 : this.total) / (this.size == 0 ? 1 : this.size)
        );
      },
    },
  },
};
</script>

// Frontend/angular/src/app/ui/data-table/data-table.component.ts
import { Component } from '@angular/core';
var obj = require('object-path');

// user imports
import { BaseComponent } from '../base.component';
import { CdkDragDrop } from '@angular/cdk/drag-drop';

@Component({
	selector: 'data-table',
	templateUrl: './data-table.component.html',
})
export class DataTableComponent extends BaseComponent {
	///
	_rows = [];
	get rows() {
		if (this.data && this.uiElement.key) {
			this._rows = obj.get(this.data, this.uiElement.key);
		}

		if (typeof this._rows != 'undefined' && !Array.isArray(this._rows)) this._rows = [this._rows];

		return this._rows;
	}

	set rows(v: any) {
		if (this.data && this.uiElement.key) {
			obj.set(this.data, this.uiElement.key, v);
		}

		// set default when value is empty
		if (!v && this.uiElement.key && this.uiElement.default) {
			let defaultValue = this.uiElement.default;
			try {
				defaultValue = eval(this.uiElement.default);
			} catch (e) {
				console.error(e);
			}
			obj.set(this.data, this.uiElement.key, defaultValue);
		}
	}

	// pagination information
	total: number = 0;
	page: number = 0;
	size: number = 0;

	ngOnInit() {
		super.ngOnInit();
		// check if there is any page configuration available
		this.getPage();

		// download data through rest web services
		this.requestDownload();

		// event handler
		this.onEvent = this.event.onEvent.subscribe(event => this.eventHandler(event));
	}

	eventHandler(event) {
		if (event && (!event.key || event.key == this.uiElement.key)) {
			if (event.name == 'refresh' && (!event.key || event.key == this.uiElement.key)) {
				// run refresh script
				if (this.uiElement.refresh) {
					try {
						eval(this.uiElement.refresh);
					} catch (e) {
						console.error(e);
					}
				}
				setTimeout(() => this.requestDownload(), 0);
			} else if (event.name == 'pagination' && (!event.key || event.key == this.uiElement.key)) {
				this.page = event.page;
				this.size = event.size;
				setTimeout(() => this.requestDownload(), 0);
			}
		}
	}

	ngOnDestroy() {
		super.ngOnDestroy();
		this.onEvent.unsubscribe();
	}

	// Get Pagination information
	getPage() {
		let params = this.nav.getParams();

		// default page is 1
		if (!this.page) {
			this.page = 1;
			// if nav param has page then use it
			if (this.uiElement.externalPaging != false && params['page']) {
				this.page = params['page'];
			}
		}

		// if the page size is determined in the url then use that otherwise use the one from the uiElement
		if (!this.size) {
			this.size = this.uiElement.size ? this.uiElement.size : 10;
			// if nav param has page then use it
			if (this.uiElement.externalPaging != false && params['size']) {
				this.size = params['size'];
			}
		}
	}

	// setting page will set the values to the URL
	setPage(page, size) {
		// save pagination
		this.page = page;
		this.size = size;

		// parameters
		// do not set pagination when card or list
		if (this.uiElement.tableType != 'card' && this.uiElement.tableType != 'list') {
			if (this.uiElement._id) {
				this.nav.setParam('page', this.page);
				this.nav.setParam('size', this.size);
			}
		}
	}

	requestDownload(pageInfo?) {
		// get page
		this.getPage();

		// set pagination
		if (!pageInfo) pageInfo = { offset: this.page - 1 };

		// save the pagination passed by data-table
		this.setPage(pageInfo.offset + 1, this.size);

		// download data through rest web services
		let src = this.uiElement.src;
		if (src) {
			try {
				src = eval(src);
			} catch (e) {
				console.error(e);
			}
			// look at query params and pass it on to the request
			let data = this.uiElement.data;
			// apply nav parameters if necessary
			if (this.uiElement.useNavParams != false) {
				let params = this.nav.getParams();
				delete params['_id'];
				data = Object.assign({}, data, params);
			}
			// apply pagination
			data = Object.assign(data, {
				page: this.page,
				size: this.size,
			});

			// sorting options
			if (this.uiElement.sort) {
				if (this.sort.dir == 'asc') data['_sort'] = this.sort.prop;
				else if (this.sort.dir == 'desc') data['_sort_desc'] = this.sort.prop;
			}

			let options = {};
			if (this.uiElement.options) {
				options = this.uiElement.options;
				try {
					options = eval(`${options}`);
				} catch {}
			}

			if (this.uiElement.preProcess) {
				try {
					eval(this.uiElement.preProcess);
				} catch (e) {
					console.error(e);
				}
			}

			// send REST request
			this.event.send({ name: 'splash-show' }); // show splash
			this.rest
				.request(src, data, this.uiElement.method, options, this.uiElement.cached)
				.subscribe(response => this.responseDownload(response));
		} else {
			this.total = this.rows ? this.rows.length : 0;
			this.size = this.total;
		}
	}

	responseDownload(response) {
		// hide splash
		this.event.send({ name: 'splash-hide' });

		// map data from response
		let transform = this.uiElement.transform || 'response.data';
		try {
			this.rows = eval(transform);
		} catch (e) {}

		// get total records
		let transformTotal = this.uiElement.transformTotal || 'response.total';
		try {
			this.total = parseInt(eval(transformTotal));
		} catch (e) {}
		if (this.total != 0 && !this.total) this.total = this.rows.length;
	}

	sort: any;
	onSort(event: any) {
		// event.sorts.dir / prop
		this.sort = event.sorts[0];
		if (this.sort) this.requestDownload();
	}

	drop(event: CdkDragDrop<string[]>) {
		if (this.uiElement.drop) {
			try {
				eval(this.uiElement.drop);
			} catch (e) {
				console.error(e);
			}
		}
	}
}

<ngx-datatable
  *ngIf="!uiElement.tableType || uiElement.tableType == 'table'"
  [ngClass]="uiElement.class ? uiElement.class : config.get('dataTable.class')"
  [ngStyle]="uiElement.style ? uiElement.style : config.get('dataTable.style')"
  [rows]="rows"
  [externalSorting]="
    uiElement.externalSorting ? uiElement.externalSorting : false
  "
  (sort)="onSort($event)"
  [columnMode]="uiElement.columnMode ? uiElement.columnMode : 'force'"
  [headerHeight]="
    uiElement.headerHeight
      ? uiElement.headerHeight
      : config.get('dataTable.headerHeight')
  "
  [footerHeight]="
    uiElement.footerHeight
      ? uiElement.footerHeight
      : config.get('dataTable.footerHeight')
  "
  [rowHeight]="uiElement.rowHeight ? uiElement.rowHeight : 'auto'"
  [scrollbarH]="uiElement.scrollbarH ? uiElement.scrollbarH : true"
  [reorderable]="uiElement.reorderable ? uiElement.reorderable : true"
  [selectionType]="uiElement.selectionType ? uiElement.selectionType : ''"
  [groupRowsBy]="
    uiElement.group?.groupRowsBy ? uiElement.group.groupRowsBy : ''
  "
  [groupExpansionDefault]="
    uiElement.group?.groupExpansionDefault ? true : false
  "
  [count]="total"
  [offset]="page - 1"
  [limit]="size"
  (page)="requestDownload($event)"
  [externalPaging]="uiElement.externalPaging ? uiElement.externalPaging : true"
  (activate)="$event.type == 'click' ? click($event.row) : ''"
>
  <!-- Group Header Template -->
  <ngx-datatable-group-header
    *ngIf="uiElement.group?.groupRowsBy"
    [rowHeight]="uiElement.group?.rowHeight"
  >
    <ng-template let-group="group" ngx-datatable-group-header-template>
      <div
        [ngStyle]="uiElement.group?.style"
        [innerHTML]="format(group, uiElement.group?.format) | safe: 'html'"
      ></div>
    </ng-template>
  </ngx-datatable-group-header>

  <!-- Column Template -->
  <ngx-datatable-column
    *ngFor="let column of uiElement.columns"
    [name]="column.label"
    [prop]="column.key"
    [flexGrow]="column.flexGrow"
    [canAutoResize]="column.canAutoResize"
    [width]="
      column.width ? column.width : config.get('dataTable.minColumnWidth')
    "
  >
    <ng-template ngx-datatable-cell-template let-row="row" let-value="value">
      <div
        [ngStyle]="column?.style"
        [innerHTML]="format(value, column.format, row) | safe: 'html'"
        (click)="click($event, row, column.click)"
      ></div>
    </ng-template>
  </ngx-datatable-column>
</ngx-datatable>

<!-- Card List -->
<ng-container *ngIf="uiElement.tableType == 'card'">
  <cdk-virtual-scroll-viewport
    cdkDropList
    [cdkDropListData]="rows"
    (cdkDropListDropped)="drop($event)"
    [ngStyle]="
      uiElement.contentLayoutStyle
        ? uiElement.contentLayoutStyle
        : config.get('dataTable.contentLayoutStyle')
    "
    [itemSize]="total < size ? total : size"
  >
    <mat-card
      cdkDrag
      [cdkDragDisabled]="uiElement.dragNdrop != true"
      *cdkVirtualFor="let row of rows"
      (click)="click($event, row, uiElement.click)"
      [ngStyle]="
        uiElement.itemBoxStyle
          ? uiElement.itemBoxStyle
          : config.get('dataTable.itemBoxStyle')
      "
      [ngClass]="
        uiElement.itemBoxClass
          ? uiElement.itemBoxClass
          : config.get('dataTable.itemBoxClass')
      "
    >
      <ng-container *ngFor="let column of uiElement.columns">
        <ng-container
          ui-layout-wrapper
          [uiElement]="column"
          [data]="row"
        ></ng-container>
      </ng-container>
    </mat-card>
  </cdk-virtual-scroll-viewport>
  <pagination
    *ngIf="total > size"
    [key]="uiElement.key"
    [total]="total"
    [page]="page"
    [size]="size"
  ></pagination>
</ng-container>

<!-- Simple List -->
<div
  *ngIf="uiElement.tableType == 'list'"
  cdkDropListGroup
  [ngStyle]="
    uiElement.contentLayoutStyle
      ? uiElement.contentLayoutStyle
      : config.get('dataTable.contentLayoutStyle')
  "
>
  <div
    *ngFor="let row of rows"
    [ngStyle]="
      uiElement.itemBoxStyle
        ? uiElement.itemBoxStyle
        : config.get('dataTable.itemBoxStyle')
    "
    [ngClass]="
      uiElement.itemBoxClass
        ? uiElement.itemBoxClass
        : config.get('dataTable.itemBoxClass')
    "
    (click)="click($event, row, uiElement.click)"
  >
    <ng-container *ngFor="let column of uiElement.columns">
      <ng-container
        ui-layout-wrapper
        [uiElement]="column"
        [data]="row"
      ></ng-container>
    </ng-container>
  </div>
</div>
