// Frontend/vue/src/ui/Image.vue
<template>
  <img
    :class="uiElement.class"
    :style="uiElement.style"
    :src="safeEval(uiElement.src)"
    @click="click($event)"
  />
</template>

<script>
import Vue from "vue";
import Base from "./Base";
const obj = require("object-path");
const moment = require("moment");

export default Vue.component("image-loader", {
  extends: Base,
});
</script>

// Frontend/angular/src/app/ui/image/image.component.ts
import { Component } from '@angular/core';
var obj = require('object-path');

// user Imports
import { BaseComponent } from '../base.component';

@Component({
	selector: 'image',
	template: `
		<img
			*ngIf="condition(uiElement)"
			[ngStyle]="uiElement.style"
			[ngClass]="uiElement.class"
			[src]="safeEval(uiElement.src)"
			(click)="click($event)"
		/>
	`,
})
export class ImageComponent extends BaseComponent {
}
